apiVersion: v1
kind: LimitRange
metadata:
  name: recursos
  namespace: ej10
spec:
  limits:
  - default: # Límite asignado por defecto si no se especifica
      memory: 1Gi
      cpu: "1"
    defaultRequest:
      memory: 0.5Gi
      cpu: "0.5"
    max: # Máximo permitido
      memory: 1Gi
      cpu: "1"
    min: # Mínimo permitido
      memory: 0.5Gi
      cpu: "0.5"
    type: Container